trigger:
  branches:
    include:
      - veracode-upload-and-scan

pool:
  name: 'azureagent'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'

steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'
  - task: UseDotNet@2
    inputs:
      version: '8.x'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'  # Publish command performs both build and publish
      projects: "$(solution)"  # Path to your solution file
      arguments: '-c $(buildConfiguration) -o $(build.artifactStagingDirectory) /p:PublishSingleFile=true /p:PackageAsSingleFile=true'  # Arguments for publishing and single-file package
    displayName: 'Build and Publish Solution'

  #scan the artifact with veracode upload and scan
  - task: Veracode@3
    inputs:
      ConnectionDetailsSelection: 'Service Connection'
      AnalysisService: 'veracodeservice'
      veracodeAppProfile: '$(system.teamProject)'
      version: '$(build.buildNumber)'
      filepath: '$(build.artifactStagingDirectory)/app.zip'
      createProfile: true
      failBuildIfUploadAndScanBuildStepFails: true
      importResults: true
      maximumWaitTime: '360'